### ISSUE TITLE
A date of birth far in the past (e.g. 1937) is very cumbersome to enter

### ISSUE THREAD

**Issue by oleschri** [internetztube/jaukerl-ooe#4]
The custom calendar control does not have an option to directly type a date.

Suggestion: Use browser's default date input control.

**Comment by internetztube** [comment]
Thanks for the bug report. The fix should be live in a few minutes.

Old:
<img width="2160" alt="Screenshot 2021-11-18 at 14 20 57" src="https://user-images.githubusercontent.com/6382364/142423196-c87ab241-e175-4246-b6e7-e574d03f96a6.png">

New:
<img width="2160" alt="Screenshot 2021-11-18 at 14 20 59" src="https://user-images.githubusercontent.com/6382364/142423223-4982f82a-7ed5-479a-a939-ed7f8de47797.png">
